[2025-03-17T05:46:03.675+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-17T05:46:03.728+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parallel_etl_model_training.transform_raw_data scheduled__2025-03-16T00:00:00+00:00 [queued]>
[2025-03-17T05:46:03.744+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parallel_etl_model_training.transform_raw_data scheduled__2025-03-16T00:00:00+00:00 [queued]>
[2025-03-17T05:46:03.746+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-17T05:46:03.784+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): transform_raw_data> on 2025-03-16 00:00:00+00:00
[2025-03-17T05:46:03.809+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=149) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-17T05:46:03.811+0000] {standard_task_runner.py:72} INFO - Started process 175 to run task
[2025-03-17T05:46:03.813+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'parallel_etl_model_training', 'transform_raw_data', 'scheduled__2025-03-16T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/Scripts/parallel_etl_and_model_training.py', '--cfg-path', '/tmp/tmpa3ra3h0o']
[2025-03-17T05:46:03.815+0000] {standard_task_runner.py:105} INFO - Job 13: Subtask transform_raw_data
[2025-03-17T05:46:03.841+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:209: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-03-17T05:46:03.926+0000] {task_command.py:467} INFO - Running <TaskInstance: parallel_etl_model_training.transform_raw_data scheduled__2025-03-16T00:00:00+00:00 [running]> on host b4dde35c7dfd
[2025-03-17T05:46:03.927+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  if conf.get("database", "sql_alchemy_conn") == "none://":

[2025-03-17T05:46:04.076+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='parallel_etl_model_training' AIRFLOW_CTX_TASK_ID='transform_raw_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-16T00:00:00+00:00'
[2025-03-17T05:46:04.079+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-17T05:46:04.080+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-17T05:46:04.080+0000] {logging_mixin.py:190} INFO - Current task name:transform_raw_data state:running start_date:2025-03-17 05:46:03.728997+00:00
[2025-03-17T05:46:04.081+0000] {logging_mixin.py:190} INFO - Dag name:parallel_etl_model_training and current dag run status:running
[2025-03-17T05:46:04.082+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-17T05:46:04.084+0000] {parallel_etl_and_model_training.py:44} INFO - Starting data transformation
[2025-03-17T05:46:05.344+0000] {warnings.py:112} WARNING - /opt/***/dags/Scripts/parallel_etl_and_model_training.py:51: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  raw_df = pd.read_json(raw_data_json)

[2025-03-17T05:46:07.031+0000] {parallel_etl_and_model_training.py:52} INFO - Raw data loaded from XCom. Shape: (186850, 6)
[2025-03-17T05:46:08.007+0000] {warnings.py:112} WARNING - /opt/***/dags/Scripts/etl.py:72: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')

[2025-03-17T05:47:16.671+0000] {parallel_etl_and_model_training.py:55} INFO - Data cleaned. Shape: (185687, 14)
[2025-03-17T05:47:28.093+0000] {parallel_etl_and_model_training.py:58} INFO - Transformed data uploaded to processed/transformed/sales-processed.parquet
[2025-03-17T05:47:28.192+0000] {python.py:240} INFO - Done. Returned value was: True
[2025-03-17T05:47:28.224+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-17T05:47:28.225+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=parallel_etl_model_training, task_id=transform_raw_data, run_id=scheduled__2025-03-16T00:00:00+00:00, execution_date=20250316T000000, start_date=20250317T054603, end_date=20250317T054728
[2025-03-17T05:47:28.262+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-17T05:47:28.263+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-17T05:47:28.263+0000] {logging_mixin.py:190} INFO - Dag name:parallel_etl_model_training queued_at:2025-03-17 05:44:56.486571+00:00
[2025-03-17T05:47:28.264+0000] {logging_mixin.py:190} INFO - Task hostname:b4dde35c7dfd operator:PythonOperator
[2025-03-17T05:47:28.307+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-17T05:47:28.349+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-17T05:47:28.351+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
